### ISSUE TITLE
m1打包window时报错gcc_libinit_windows.c:8:10: fatal error: 'windows.h' file not found

### ISSUE THREAD

**Issue by zk3151463** [MQEnergy/chatcat#3]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/24578141/234048317-69fbacae-db7d-4b1a-894e-1d82de5381cf.png">

**Comment by chenxi2015** [comment]
建议在不同的环境电脑上进行打包

**Comment by zk3151463** [comment]
但是go本身是支持交叉编译的呀

**Comment by zk3151463** [comment]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/24578141/234373560-f8e9b6a7-7de4-4ede-9c30-206a09d803cb.png">
装了一个c++现在报这个错，可以指导下吗

**Comment by ethanchancc18** [comment]
> 

你装https://jmeubank.github.io/tdm-gcc/  
<img width="222" alt="image" src="https://user-images.githubusercontent.com/129471302/234486368-fcc99aab-d018-40eb-8995-b9edb697de27.png">
这个试一下

**Comment by zk3151463** [comment]
我是mac  m1呀

**Comment by ethanchancc18** [comment]
> 我是mac m1呀

我现在还在开发中 我研究下~

**Comment by chenxi2015** [comment]
> 我是mac m1呀

我现在还在开发中，我研究下~

**Comment by zk3151463** [comment]
好的，感谢
